add BUILDPACK_PRELAUNCH_METEOR support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -104,6 +104,14 @@ if [ -e "$APP_SOURCE_DIR"/package.json ]; then
   npm install
 fi
 
+if [ -n "${BUILDPACK_PRELAUNCH_METEOR+1}" ]; then
+  echo "-----> BUILDPACK_PRELAUNCH_METEOR: Pre-launching meteor to build packages assets"
+  # Remove the Android platform because it fails due to the Android tools not
+  # being installed, but leave the iOS platform because it's ignored.
+  HOME=$METEOR_DIR $METEOR remove-platform android || true
+  HOME=$METEOR_DIR timeout -s9 60 $METEOR --settings settings.json || true
+fi
+
 BUNDLE_DEST=/tmp/cache/build
 mkdir -p $BUNDLE_DEST
 
