changes based on AdmitHub/meteor-buildpack-horse

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,96 +1,153 @@
 #!/bin/bash
 set -eo pipefail
 
-DIR="$(cd "$(dirname "$0")" && pwd)"
-source $DIR/common
-
-METEOR_HOME=$BUILD_DIR/.meteor/local
-PATH=$METEOR_HOME/usr/bin:$METEOR_HOME/usr/lib/meteor/bin:$PATH
-
-indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";; # mac/bsd sed: -l buffers on line boundaries
-    *)      sed -u "$c";; # unix/gnu sed: -u unbuffered (arbitrary) chunks of data
-  esac
-}
-
-status() {
-  echo "-----> $*"
-}
-
-node_version=$(curl --silent --get https://semver.io/node/resolve/0.10.x)
-
-install_node() {
-  if [ -f "$BUILD_DIR/.vendor/node/bin/node" ] ; then
-    status "Skipping Node installation. Already installed."
-    return
+# Load config vars into environment (from https://devcenter.heroku.com/articles/buildpack-api)
+export_env_dir() {
+  env_dir=$1
+  whitelist_regex=${2:-''}
+  blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+  if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+      echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" &&
+      export "$e=$(cat $env_dir/$e)"
+      :
+    done
   fi
-
-  # Download node from Heroku's S3 mirror of nodejs.org/dist
-  status "Downloading and installing node $node_version"
-  NODE_INSTALLER=node-installer.tar.gz
-  NODE_URL="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
-  curl $NODE_URL > $NODE_INSTALLER
-  tar xzf $NODE_INSTALLER -C $BUILD_DIR
-
-  # Move node (and npm) into ./.vendor and make them executable
-  mkdir -p $BUILD_DIR/.vendor
-  mv $BUILD_DIR/node-v$node_version-linux-x64 $BUILD_DIR/.vendor/node
-  chmod +x $BUILD_DIR/.vendor/node/bin/*
-  PATH=$BUILD_DIR/.vendor/node/bin:$PATH
 }
 
-install_meteor() {
-  if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
-    status "Skipping Meteor installation. Already installed."
-    return
-  fi
+export_env_dir $3
 
-  # status "Install Meteor"
-  # export PATH=/usr/bin:$PATH # necessary for install script to run from URL
-  # curl https://install.meteor.com | sh
-  status "Downloading Meteor install script"
-  METEOR_INSTALL_SCRIPT=install_meteor.sh
-  curl https://install.meteor.com/ > $METEOR_INSTALL_SCRIPT
-
-  status "Installing Meteor connected to $MONGO_URL"
-  sed -e '/^#!\/bin\/sh/ s/$/ -x/' \
-    -e 's/set -/#set -/' \
-    -e 's/curl --progress-bar --fail.*/curl "$TARBALL_URL" > meteor-bundle.tgz; tar -xzf meteor-bundle.tgz -C "$INSTALL_TMPDIR" -o/' \
-    $METEOR_INSTALL_SCRIPT > install-meteor-verbose.sh
-  chmod +x install-meteor-verbose.sh
-
-  status "Execute ./install-meteor-verbose.sh"
-  ./install-meteor-verbose.sh
-  status "Done"
-
-  status "Updating PATH with Meteor"
-  PATH=$HOME/.meteor:$PATH
-}
-
-build() {
-  (
-    cd $BUILD_DIR
-    status "Building meteor bundle"
-    meteor build --directory deploy --server http://localhost:3000
-    cd deploy/bundle/programs/server
-    status "Installing npm dependencies"
-    npm install 2>&1 | indent
-    mv $BUILD_DIR/.vendor $BUILD_DIR/vendor
-  )
-}
-
-[ ! -d $BUILD_DIR ] && mkdir $BUILD_DIR
-[ ! -d $CACHE_DIR ] && mkdir $CACHE_DIR
-
-install_node
-install_meteor
-build
-
-status "Checking for post_compile script"
-if [ -f $BUILD_DIR/bin/post_compile ] ; then
-    status "Running post_compile hook"
-    chmod +x $BUILD_DIR/bin/post_compile
-    $BUILD_DIR/bin/post_compile
+# Enable verbose debugging if configured to -- though this has to come after
+# we've loaded environment configs.
+if [ -n "${BUILDPACK_VERBOSE+1}" ]; then
+  set -x
 fi
+
+if [ -z "$MONGO_URL" ] ; then
+  echo "MONGO_URL is not defined."
+  exit 1
+fi
+
+if [ -z "$ROOT_URL" ] ; then
+  echo "ROOT_URL is not defined."
+  exit 1
+fi
+
+# Get the path to dir one above this file.
+BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
+# Get the directory our app is checked out in (the "BUILD_DIR"), passed by Heroku
+APP_CHECKOUT_DIR=$1
+
+#
+# Find the meteor app ($APP_SOURCE_DIR).
+#
+
+# Set meteor app dir's location to the root of the git repo, plus the value of
+# METEOR_APP_DIR (which defaults empty).  If you put the meteor app in src/ or
+# some other subdirectory, define METEOR_APP_DIR.
+APP_SOURCE_DIR="${APP_CHECKOUT_DIR}"
+if [ -n "$METEOR_APP_DIR" ]; then
+  APP_SOURCE_DIR="${APP_SOURCE_DIR}/${METEOR_APP_DIR}"
+fi
+
+# Try "$APP_SOURCE_DIR/app/" if meteor app isn't there (the "Iron scaffolding
+# tool" default).
+if [ ! -d "$APP_SOURCE_DIR/.meteor" ] && [ -d "$APP_SOURCE_DIR/app/.meteor" ]; then
+  APP_SOURCE_DIR="$APP_SOURCE_DIR/app/"
+fi
+if [ ! -d "$APP_SOURCE_DIR/.meteor" ]; then
+  echo "FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' supdirectory.  (Tried ${APP_SOURCE_DIR})"
+  exit 1
+fi
+
+# Where we will install meteor. Has to be outside the APP_CHECKOUT_DIR.
+METEOR_DIR=`mktemp -d "$BUILDPACK_DIR"/meteor-XXXX`
+# Where we'll put things we compile.
+COMPILE_DIR_SUFFIX=".meteor/heroku_build"
+COMPILE_DIR="$APP_CHECKOUT_DIR"/"$COMPILE_DIR_SUFFIX"
+# Try to minimize meteor's printing
+METEOR_PRETTY_OUTPUT=0
+
+# Create directories as needed.
+mkdir -p "$APP_CHECKOUT_DIR" "$METEOR_DIR" "$COMPILE_DIR"
+
+# Update the path so we get npm, etc.
+PATH="$METEOR_DIR/.meteor:$COMPILE_DIR/bin:$PATH"
+
+#
+# Install node
+#
+if [ -f "$COMPILE_DIR/bin/node" ] ; then
+  echo "-----> Installing node"
+  NODE_VERSION=`curl -sS --get https://semver.io/node/resolve/0.10.x`
+  NODE_URL="http://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
+  curl -sS $NODE_URL -o - | tar -zxf - -C $COMPILE_DIR --strip 1
+fi
+
+export npm_config_prefix="$COMPILE_DIR"
+export CPATH="$COMPILE_DIR"/include
+export CPPPATH="$CPATH"
+
+#
+# Install meteor
+#
+echo "-----> Installing meteor"
+curl -sS https://install.meteor.com | HOME="$METEOR_DIR" /bin/sh
+METEOR="$METEOR_DIR/.meteor/meteor" # The meteor binary.
+
+CUR_RELEASE=`HOME=$METEOR_DIR $METEOR --version | sed -e 's/Meteor /METEOR@/'`
+APP_RELEASE=`cat "$APP_SOURCE_DIR/.meteor/release"`
+if test "$CUR_RELEASE" != "$APP_RELEASE" ; then
+  # Sort CUR_RELEASE and APP_RELEASE and find the oldest
+  OLDER_RELEASE=`echo "$CUR_RELEASE\n$APP_RELEASE" | sort --version-sort | head -n1`
+  if [ "$CUR_RELEASE" = "$OLDER_RELEASE" ]; then
+    echo "-----> Upgrading meteor to $APP_RELEASE"
+    HOME=$METEOR_DIR $METEOR update --release $APP_RELEASE
+  fi
+fi
+
+#
+# Build the meteor app!
+#
+echo "-----> Bundling bundle"
+cd $APP_SOURCE_DIR
+
+# If we use npm on root, run npm install.
+if [ -e "$APP_SOURCE_DIR"/package.json ]; then
+  npm install
+fi
+# Now on to bundling. Don't put the bundle in $APP_CHECKOUT_DIR, or it will
+# recurse, trying to bundle up its own bundling.
+BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
+echo "-----> Building Meteor with ROOT_URL: $ROOT_URL"
+HOME=$METEOR_DIR $METEOR build --server $ROOT_URL --directory $BUNDLE_DEST
+mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
+rmdir $BUNDLE_DEST
+
+# If we use npm, run npm install.
+if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
+  cd "$COMPILE_DIR"/app/programs/server && npm install
+fi
+
+#
+# Environment
+#
+# Add an export of PATH which includes our compile dir, etc.
+echo "-----> Adding PATH environment"
+mkdir -p "$APP_CHECKOUT_DIR"/.profile.d
+cat > "$APP_CHECKOUT_DIR"/.profile.d/path.sh <<EOF
+  #!/bin/sh
+  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
+  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
+EOF
+
+#
+# Extras
+#
+
+# source scripts in 'extra' dir, if any.  Create them for custom stuff like
+# binary dependencies, additional environment settings, etc.
+echo "-----> Running extras"
+for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
+  . "$BUILDPACK_DIR"/extra/$file
+done
